
TRANSLATIONS = {
    "de": {
        "app_title": "DesktopCleaner Pro - Dein Desktop, aber ästhetisch",
        "nav_dashboard": "🏠 Dashboard",
        "nav_clean": "🧹 Aufräumen",
        "nav_search": "🔍 Suche",
        "nav_stats": "📊 Statistik",
        "nav_settings": "⚙️ Einstellungen",
        "system_section": "System",
        "ram_label": "RAM: {percent}%",
        "cpu_label": "CPU: {percent}%",
        "disk_label": "Disk: {percent}%",
        "welcome_title": "Willkommen zurück! 👋",
        "welcome_sub": "Dein Desktop ist dein digitales Zuhause. Lass uns ihn gemeinsam schön halten.",
        "stat_total_files": "Gesamt Dateien",
        "stat_storage": "Speicher",
        "stat_categories": "Kategorien",
        "stat_last_scan": "Letzter Scan",
        "quick_clean_title": "⚡ Schnell-Aufräumen",
        "quick_clean_desc": "Ein Klick, alles sortiert. Dateien werden intelligent in Ordner wie Bilder, PDFs, Dokumente usw. einsortiert.",
        "quick_clean_btn": "🧹 JETZT AUFRÄUMEN",
        "ready_to_clean": "Bereit zum Aufräumen",
        "moving_file": "Verschiebe: {name}...",
        "sorted_files": "✅ {count} Dateien sortiert!",
        "already_sorted": "Alles bereits sortiert",
        "recent_files_title": "📁 Aktuelle Dateien",
        "clean_center_title": "🧹 Desktop Aufräum-Zentrale",
        "clean_center_desc": "Wähle aus wie aufgeräumt werden soll. Alle Dateien bleiben erhalten, nur besser sortiert.",
        "target_folders_label": "Ziel-Ordner die erstellt werden:",
        "files_to_sort_label": "Zu sortierende Dateien",
        "files_to_sort_count": "{count} Dateien zum Sortieren",
        "col_filename": "Dateiname",
        "col_target": "Ziel-Ordner",
        "col_size": "Größe",
        "col_type": "Typ",
        "col_category": "Kategorie",
        "col_path": "Pfad",
        "col_name": "Name",
        "clean_start_btn": "✨ AUFRÄUMEN STARTEN",
        "search_title": "🔍 Datei-Suche",
        "search_placeholder": "Dateiname suchen...",
        "search_results_title": "Suchergebnisse",
        "search_show_explorer": "📂 Im Explorer zeigen",
        "search_open": "▶️ Öffnen",
        "stats_title": "📊 Speicher & Datei-Statistik",
        "stats_dist_title": "Dateitypen Verteilung",
        "stats_storage_title": "Speicher nach Kategorie",
        "stats_storage_mb_title": "Speicher nach Kategorie (MB)",
        "settings_title": "⚙️ Einstellungen",
        "auto_clean_title": "🔁 Automatisches Aufräumen",
        "auto_clean_desc": "Lässt den Desktop automatisch in Intervallen aufräumen. Perfekt wenn du viel herunterlädst.",
        "auto_clean_enable": "Auto-Clean aktivieren:",
        "interval_label": "Intervall:",
        "interval_5m": "5 Minuten",
        "interval_15m": "15 Minuten",
        "interval_30m": "30 Minuten",
        "interval_1h": "1 Stunde",
        "interval_2h": "2 Stunden",
        "auto_disabled": "⏸️ Auto-Clean ist deaktiviert",
        "auto_active": "🟢 Auto-Clean aktiv - alle {interval}",
        "about_title": "ℹ️ Über diese App",
        "about_text": "DesktopCleaner Pro v1.2 - Gebaut mit Liebe für einen ästhetischen Desktop.\n\n• Sortiert nach echten Windows Kategorien (Bilder, Dokumente, etc.)\n• Erstellt Ordner automatisch wenn sie fehlen\n• Zeigt Live RAM/CPU/Disk Verbrauch\n• Moderne Animationen & Dark Mode\n• Suche mit direktem Öffnen\n• Statistik-Charts mit Matplotlib\n• Jetzt bilingual DE/EN\n\nTipp: Rechtsklick im Explorer -> Senden an -> DesktopCleaner für schnellen Zugriff einrichten.",
        "lang_title": "🌐 Sprache / Language",
        "lang_desc": "Wähle deine bevorzugte Sprache. Die App merkt sich deine Auswahl.",
        "lang_label": "Sprache:",
        "lang_de": "Deutsch",
        "lang_en": "English",
        "nothing_title": "Nichts zu tun",
        "nothing_msg": "Dein Desktop ist bereits super aufgeräumt! ✨",
        "done_title": "Fertig! 🎉",
        "done_msg": "{moved} von {total} Dateien wurden sortiert!\n\nDein Desktop ist jetzt clean und ästhetisch.",
        "error_open": "Konnte Datei nicht öffnen:\n{error}",
        "file_count_header": "{count} Dateien • {size}",
        "files_on_desktop": "{count} Dateien auf dem Desktop",
        "hits": "{count} Treffer",
        "last_action_scan": "Scan um {time}",
        "last_action_clean": "Aufgeräumt ({count} verschoben) um {time}",
        "last_action_auto_on": "Auto-Aufräumen aktiv ({interval} Min)",
        "last_action_auto_off": "Auto-Aufräumen deaktiviert",
        "disk_usage_text": "Belegt: {used} / {total} ({percent}%)",
        "just_now": "gerade eben",
    },
    "en": {
        "app_title": "DesktopCleaner Pro - Your Desktop, but aesthetic",
        "nav_dashboard": "🏠 Dashboard",
        "nav_clean": "🧹 Clean Up",
        "nav_search": "🔍 Search",
        "nav_stats": "📊 Statistics",
        "nav_settings": "⚙️ Settings",
        "system_section": "System",
        "ram_label": "RAM: {percent}%",
        "cpu_label": "CPU: {percent}%",
        "disk_label": "Disk: {percent}%",
        "welcome_title": "Welcome back! 👋",
        "welcome_sub": "Your desktop is your digital home. Let's keep it beautiful together.",
        "stat_total_files": "Total Files",
        "stat_storage": "Storage",
        "stat_categories": "Categories",
        "stat_last_scan": "Last Scan",
        "quick_clean_title": "⚡ Quick Clean",
        "quick_clean_desc": "One click, everything sorted. Files are intelligently organized into folders like Images, PDFs, Documents and more.",
        "quick_clean_btn": "🧹 CLEAN NOW",
        "ready_to_clean": "Ready to clean",
        "moving_file": "Moving: {name}...",
        "sorted_files": "✅ {count} files sorted!",
        "already_sorted": "Already sorted",
        "recent_files_title": "📁 Recent Files",
        "clean_center_title": "🧹 Desktop Clean Center",
        "clean_center_desc": "Choose how to clean up. All files stay safe, just better organized.",
        "target_folders_label": "Target folders to be created:",
        "files_to_sort_label": "Files to sort",
        "files_to_sort_count": "{count} files to sort",
        "col_filename": "File name",
        "col_target": "Target Folder",
        "col_size": "Size",
        "col_type": "Type",
        "col_category": "Category",
        "col_path": "Path",
        "col_name": "Name",
        "clean_start_btn": "✨ START CLEANING",
        "search_title": "🔍 File Search",
        "search_placeholder": "Search filename...",
        "search_results_title": "Search Results",
        "search_show_explorer": "📂 Show in Explorer",
        "search_open": "▶️ Open",
        "stats_title": "📊 Storage & File Statistics",
        "stats_dist_title": "File Type Distribution",
        "stats_storage_title": "Storage by Category",
        "stats_storage_mb_title": "Storage by Category (MB)",
        "settings_title": "⚙️ Settings",
        "auto_clean_title": "🔁 Automatic Cleanup",
        "auto_clean_desc": "Let your desktop clean itself automatically at intervals. Perfect if you download a lot.",
        "auto_clean_enable": "Enable Auto-Clean:",
        "interval_label": "Interval:",
        "interval_5m": "5 Minutes",
        "interval_15m": "15 Minutes",
        "interval_30m": "30 Minutes",
        "interval_1h": "1 Hour",
        "interval_2h": "2 Hours",
        "auto_disabled": "⏸️ Auto-Clean is disabled",
        "auto_active": "🟢 Auto-Clean active - every {interval}",
        "about_title": "ℹ️ About this App",
        "about_text": "DesktopCleaner Pro v1.2 - Built with love for an aesthetic desktop.\n\n• Sorts by real Windows categories (Images, Documents, etc.)\n• Creates folders automatically if missing\n• Shows live RAM/CPU/Disk usage\n• Modern animations & dark mode\n• Search with direct open\n• Statistics charts with Matplotlib\n• Now bilingual DE/EN\n\nTip: Right-click in Explorer -> Send to -> DesktopCleaner for quick access.",
        "lang_title": "🌐 Language / Sprache",
        "lang_desc": "Choose your preferred language. The app remembers your choice.",
        "lang_label": "Language:",
        "lang_de": "Deutsch",
        "lang_en": "English",
        "nothing_title": "Nothing to do",
        "nothing_msg": "Your desktop is already super clean! ✨",
        "done_title": "Done! 🎉",
        "done_msg": "{moved} of {total} files were sorted!\n\nYour desktop is now clean and aesthetic.",
        "error_open": "Could not open file:\n{error}",
        "file_count_header": "{count} files • {size}",
        "files_on_desktop": "{count} files on desktop",
        "hits": "{count} hits",
        "last_action_scan": "Scan at {time}",
        "last_action_clean": "Cleaned ({count} moved) at {time}",
        "last_action_auto_on": "Auto-clean active ({interval} min)",
        "last_action_auto_off": "Auto-clean disabled",
        "disk_usage_text": "Used: {used} / {total} ({percent}%)",
        "just_now": "just now",
    }
}
